
name: Deploy Ingestion ADF
run-name: Deploy Ingestion ADF

on:
  workflow_dispatch: 
  push:
    paths:
      - 'github/workflows/'

    
jobs:
  build_ARM_templates:
    name: Build ARM templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0
        
      - name: Export ARM templates
        id: export
        uses: Azure/data-factory-export-action@v1.2.0
        with:
          path: Ingestion

      - name: Upload ARM templates artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: armtemplates
          path: ${{steps.export.outputs.arm-template-directory }}
          if-no-files-found: error
          
  deploy_to_uat_ingestion_adf:
    needs: [build_ARM_templates]
    name: Deploy to TEST ADF
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.TST_SPN_CREDS_JSON}}
          enable-AzPSSession: true
      - name: Download ARM templates artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: armtemplates
          path: armtemplates

      - name: Deploy to TEST
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: "rg_tst"
          dataFactoryName: "tstADF110"
          armTemplateFile: ./ARMTemplateForFactory.json
          armTemplateParametersFile: ./tst_ARMTemplateParametersForFactory.json

################### End of workflow file ###################
